name: iframe-storage

on:
  push:
    branches:
      - master
    paths:
      - iframe-storage/**
      - .github/workflows/iframe-storage.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iframe-storage

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DEPLOY_PROJECT_NAME: safari-iframe-storage-always-hurts-my-work
          DEPLOY_BRANCH: master
        run: |
          npx wrangler pages deploy . \
          --project-name "${DEPLOY_PROJECT_NAME}" \
          --branch "${DEPLOY_BRANCH}" \
          --commit-dirty=true
